### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by jordanwillis** [vladimirkocic/sql-scratch-capstone-turn-in#1]
## Rubric Score
 
### Criteria 1: Report: Are conclusions clear and supported by evidence in all answers?
* _Score Level:_ 4/4
* _Comment(s):_ Absolutely great job on your presentation!  Not only did it contain interesting and correct conclusions supported by data evidence and queries, it was also very well put together and visually looked great.

I particularly liked how you provided several different opinions about what some questions have lower response rates and your final data insights.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4/4
* _Comment(s):_ All your queries look great and correctly manipulate the data.
 
### Criteria 3: Query Formatting
* _Score Level:_ 3/4
* _Comment(s):_ In general your formatting is pretty good however it's especially important to ensure your more complex queries are properly formatted.  Remember this is the single way to improve your query readability.

https://github.com/vladimirkocic/sql-scratch-capstone-turn-in/blob/545426c6bacd512dae3f87022b72b02f09e605ca/Vladimir%20Kocic/code.sql#L157-L186
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4
* _Comment(s):_ It is very clear that you have a great understanding of the underlying concepts and terminology that are at play here.  I'm glad that you have learned so much!

 ### 15/16
Overall you did a fantastic job on this project.  Everything was basically perfect and any business leader would be very happy to receive a report and analysis such as this.

**Comment by vladimirkocic** [comment]
Thank you so much for your review! I really appreciate you working on Saturday.
